# Generated by Django 4.1.2 on 2023-10-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0008_alter_card_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
