# Generated by Django 4.1.2 on 2023-10-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0009_card_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="password",
            field=models.CharField(
                help_text="If there is no password, type n/a", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="username",
            field=models.CharField(
                help_text="If there is no username, type n/a", max_length=128
            ),
        ),
    ]
